### ISSUE TITLE
Cannot build the docker image 

### ISSUE THREAD

**Issue by adolic** [gerkone/pyTORCS-docker#2]
When attempting to build a image I get a following error:

```
Step 14/23 : RUN make clean
 ---> Running in dc674d147df8
make[1]: Entering directory '/torcs/src'
make[2]: Entering directory '/torcs/src/libs'
make[3]: Entering directory '/torcs/src/libs/confscreens'
rm -f  controlconfig.o graphconfig.o mouseconfig.o driverconfig.o joystickconfig.o simuconfig.o soundconfig.o openglconfig.o  .depend libconfscreens.so   *~
make[3]: Leaving directory '/torcs/src/libs/confscreens'
make[3]: Entering directory '/torcs/src/libs/racescreens'
rm -f  trackselect.o driverselect.o results.o pitmenu.o loadingscreen.o racemenu.o miscscreens.o fileselect.o carsetupscreen.o  .depend libracescreens.so   *~
make[3]: Leaving directory '/torcs/src/libs/racescreens'
make[3]: Entering directory '/torcs/src/libs/robottools'
rm -f  rttrack.o rttelem.o  .depend librobottools.so   *~
make[3]: Leaving directory '/torcs/src/libs/robottools'
make[3]: Entering directory '/torcs/src/libs/txml'
make[4]: *** gennmtab: No such file or directory.  Stop.
make[4]: Entering directory '/torcs/src/libs/txml'
make[4]: Leaving directory '/torcs/src/libs/txml'
make[3]: *** [/torcs/Make-default.mk:684: cleansubdirs] Error 1
make[3]: Leaving directory '/torcs/src/libs/txml'
make[2]: *** [/torcs/Make-default.mk:684: cleansubdirs] Error 1
make[2]: Leaving directory '/torcs/src/libs'
make[1]: *** [/torcs/Make-default.mk:684: cleansubdirs] Error 1
make[1]: Leaving directory '/torcs/src'
make: *** [/torcs/Make-default.mk:684: cleansubdirs] Error 1
The command '/bin/sh -c make clean' returned a non-zero code: 2
```

Any ideas why?

**Comment by gerkone** [comment]
Hey Antonio, thanks for the report
Can you provide some more info and how to reproduce this? Did you change anything?
I'll try to look into this in the next days
In the meantime you can use the image pulled from dockerhub

**Comment by adolic** [comment]
Hi Gianluca,

(`4b build the torcs image yourself`) I have just followed the installation instructions for building the docker image using the dockerfile from the repo. 

(`4a pull the torcs image`) When using image from the dockerhub everything "starts" fine but when I go inside the container `/torcs` folder is empty.
 
![Screenshot from 2022-01-01 12-19-29](https://user-images.githubusercontent.com/87640308/147849393-4a47bc31-b251-448d-849f-a33c96d7859e.png)

**Comment by gerkone** [comment]
So

- `4a pull the torcs image` -- `/torcs` should be empty. It's the build directory the torcs source gets copied and build. I remove it at the end of the dockerfile to save image space.

- `4b build the torcs image yourself` -- I'll try as soon as I can. As a quick fix could you try to remove 
https://github.com/gerkone/pyTORCS-docker/blob/01bfb15005b2d940f315a03b7dec20a68b0e92d9/torcs/Dockerfile#L28 from the dockerfile and build again?

**Comment by gerkone** [comment]
Hey. Sorry for the long wait. I noticed there was a missing subpackage (gennmtab), probably due to a gitignore error.
Could you please try again now?

**Comment by adolic** [comment]
Thank you :+1: , I can confirm that it works now.
