### ISSUE TITLE
Host installation error

### ISSUE THREAD

**Issue by colinzhaoxp** [gerkone/pyTORCS-docker#3]
Thanks your great work!
Now I meet a problem,  when I try to install your changed Torcs on my  Ubuntu 18.04
I followed `pyTORCS-docker/torcs/README.md`, and when I input `make`, it show me some errors.
![Snipaste_2022-01-19_13-27-35](https://user-images.githubusercontent.com/48939690/150069613-8e1b791b-9435-4513-b626-3c23a8a7a990.png)

would you like give me some advice?
.

**Comment by gerkone** [comment]
Hey. Thanks for the report.
I noticed there was a missing subpackage (gennmtab), probably due to a gitignore error.
Could you please try again now?

**Comment by colinzhaoxp** [comment]
> Hey. Thanks for the report. I noticed there was a missing subpackage (gennmtab), probably due to a gitignore error. Could you please try again now?

Thanks your answer!
I tried it again, and this time no error appeared.
YES! it works very well.
