### ISSUE TITLE
Distorted image

### ISSUE THREAD

**Issue by anshdavid** [gerkone/pyTORCS-docker#5]
Hey, I ran with vision but i am getting a distorted image! Can you guide me ?

![984](https://user-images.githubusercontent.com/49544120/151667518-23614d53-6fc6-43d4-8c40-728b0e852f0c.jpg)

**Comment by gerkone** [comment]
Hey David. Thanks fort the report. I'll look into this in the next days.

In the meantime can you give me some info on reproducibility?
- how do you plot the image?
- did you install torcs on your host?
- do all frames look like this?

**Comment by anshdavid** [comment]
Hey @gerkone , That error is on me. Accidentally swapped places for width and height of the vision buffer on my end. Thanks
