### ISSUE TITLE
Error during launch of pytorcs.py

### ISSUE THREAD

**Issue by MattiaCarolo** [gerkone/pyTORCS-docker#6]
Hi, I was trying to run your code but I can't pass past the the initialization. When I try to run python pytorcs.py it returns me this error

```
Traceback (most recent call last):
  File "driver/launch.py", line 4, in <module>
    import importlib.util
ImportError: No module named util
```

I tried running it with different versions of python but all to no avail.

**Comment by gerkone** [comment]
Hey Mattia. I can’t access a pc right now. Are you sure you are using python3?

**Comment by MattiaCarolo** [comment]
Yeah to be sure I tried python, python3 and pyton3.8 but always same error message

**Comment by MattiaCarolo** [comment]
I managed to make it run after reinstalling ubuntu 20.04. Tried to understand what was wrong but all to no avail sorry for the hassle

**Comment by gerkone** [comment]
Glad you solved, sorry I wasn’t any more helpful. The only thing that came to mind was that your python binaries were mixed up and you were actually running python2 regardless
